name: SonarQube Scan and Report

on:
  push:
    branches:
      - '**'

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    name: SonarQube Scan & Report

    env:
      SONAR_HOST_URL: https://your-sonarqube-domain
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Sonar packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=python \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.html.enabled=true \
            -Dsonar.report.export.path=sonar-report.html

      - name: Upload SonarQube HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: sonar-html-report
          path: sonar-report.html
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Fetch SonarQube Metrics as JSON
        run: |
          PROJECT_KEY="your_project_key"
          AUTH_HEADER="Authorization: Basic $(echo -n '${{ env.SONAR_TOKEN }}:' | base64)"
          
          curl -s -H "$AUTH_HEADER" "$SONAR_HOST_URL/api/measures/component?component=$PROJECT_KEY&metricKeys=bugs,vulnerabilities,security_hotspots_reviewed,code_smells,coverage,duplicated_lines_density,ncloc" \
            -o sonar-report.json

      - name: Convert JSON Report to Markdown
        run: |
          echo "### SonarQube Metrics Report" > sonar-summary.md
          jq -r '.component.measures[] | "* \(.metric | gsub("_"; " ") | ascii_upcase): \(.value)"' sonar-report.json >> sonar-summary.md
          cat sonar-summary.md

      - name: Upload Markdown Summary
        uses: actions/upload-artifact@v3
        with:
          name: sonar-metrics-summary
          path: sonar-summary.md
