name: SonarQube Scan

on:
  push:
    branches:
      - '**'

jobs:
  sonarqube:
    name: SonarQube Analysis and Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=python \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.scm.disabled=true \
            -Dsonar.report.export.path=sonar-report.html \
            -Dsonar.html.enabled=true

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonar-report
          path: sonar-report.html
